/*
 * HtmlShowDialog.java
 *
 * Created on 11 Февраль 2005 г., 11:07
 */

package net.sf.jpackit.ui.swing;

import java.awt.Point;

/**
 *
 * @author  eisst
 */
public class HtmlShowDialog extends javax.swing.JDialog {
    
    /** Creates new form HtmlShowDialog */
    public HtmlShowDialog(java.awt.Frame parent, boolean modal, String title, String html) {
        super(parent, modal);
        setTitle(title);
        initComponents();
        htmlViewerPane.setEditorKit(new javax.swing.text.html.HTMLEditorKit());
        htmlViewerPane.setContentType("text/html");
        htmlViewerPane.setText(html);
        htmlViewerPane.setCaretPosition(0);
        setLocationRelativeTo(parent);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        htmlViewerPane = new javax.swing.JTextPane();

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(505, 30));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(505, 360));
        htmlViewerPane.setEditable(false);
        jScrollPane1.setViewportView(htmlViewerPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 485;
        gridBagConstraints.ipady = 343;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane htmlViewerPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
