/*
 * Copyright 2004-2005 Ignat Aleksandrov, Kamil Shamgunov
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.sf.jpackit.ui.swing;

import java.text.MessageFormat;
import net.sf.jpackit.builder.JarPackageBuilder;
import net.sf.jpackit.config.BuildConfiguration;
import net.sf.jpackit.config.props.PropertiesBuildConfigurationManager;
import net.sf.jpackit.config.validator.BuildConfigurationError;
import net.sf.jpackit.config.validator.BuildConfigurationValidator;
import net.sf.jpackit.util.JarScanner;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileFilter;
import java.awt.event.ItemListener;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import net.sf.jpackit.util.MiscUtils;

/**
 * Main application frame
 *
 * @author Kamil K. Shamgunov
 */

public class JFrameForm extends javax.swing.JFrame implements DocumentListener, ItemListener, WindowListener {
    
    private ArrayList jarsList = new ArrayList();
    private boolean changed;
    private File bcFile;
    private HtmlShowDialog helpDialog = null;
    private HtmlShowDialog licenceDialog = null;
    private HtmlShowDialog changesDialog = null;
    private HtmlShowDialog faqDialog = null;
    private AboutJDialog aboutDialog = null;
    
    /**
     * Creates new form JFrameForm
     */
    public JFrameForm() {
        initComponents();
        postInit();
    }
    
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        baseDirTextField = new javax.swing.JTextField();
        bdChooseButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jarsLocationTextField = new javax.swing.JTextField();
        jlChooseButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pkgLocationTextField = new javax.swing.JTextField();
        plChooseButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pkgNameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        predefArgsTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        defaultArgsTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pkgTypeComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        mainClassTextField = new javax.swing.JTextField();
        mcChooseButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        mainJarTextField = new javax.swing.JTextField();
        mjChooseButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        statusBarLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        newFileMenuItem = new javax.swing.JMenuItem();
        fileOpenMenutem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        fileSaveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        exitMenuItem = new javax.swing.JMenuItem();
        buildMenu = new javax.swing.JMenu();
        validateMenuItem = new javax.swing.JMenuItem();
        buildPackageMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        licenseMenuItem = new javax.swing.JMenuItem();
        faqMenuItem = new javax.swing.JMenuItem();
        changesMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("JPackIt");
        setFont(new java.awt.Font("Tahoma", 0, 10));
        setResizable(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102)), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("main_frame_panel_title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(505, 300));
        jLabel1.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("base_dir"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        baseDirTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 12.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(baseDirTextField, gridBagConstraints);

        bdChooseButton.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("choose_button"));
        bdChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdChooseButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel1.add(bdChooseButton, gridBagConstraints);

        jLabel2.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("dependant_jars"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jarsLocationTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 12.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(jarsLocationTextField, gridBagConstraints);

        jlChooseButton.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("choose_button"));
        jlChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlChooseButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel1.add(jlChooseButton, gridBagConstraints);

        jLabel3.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("pkg_location"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        pkgLocationTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 12.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pkgLocationTextField, gridBagConstraints);

        plChooseButton.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("choose_button"));
        plChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plChooseButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel1.add(plChooseButton, gridBagConstraints);

        jLabel4.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("pkg_name"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 12.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pkgNameTextField, gridBagConstraints);

        jLabel5.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("predef_args"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 12.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(predefArgsTextField, gridBagConstraints);

        jLabel6.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("def_args"));
        jLabel6.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 12.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(defaultArgsTextField, gridBagConstraints);

        jLabel7.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("pkg_type"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        pkgTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jar" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 12.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pkgTypeComboBox, gridBagConstraints);

        jLabel8.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("main_class"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 0);
        jPanel1.add(jLabel8, gridBagConstraints);

        mainClassTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 12.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(mainClassTextField, gridBagConstraints);

        mcChooseButton.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("choose_button"));
        mcChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcChooseButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel1.add(mcChooseButton, gridBagConstraints);

        jLabel9.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("main_jar"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 3, 9, 0);
        jPanel1.add(jLabel9, gridBagConstraints);

        mainJarTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 12.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(mainJarTextField, gridBagConstraints);

        mjChooseButton.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("choose_button"));
        mjChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mjChooseButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel1.add(mjChooseButton, gridBagConstraints);

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 1, 0));

        jPanel2.setBorder(new javax.swing.border.EtchedBorder(null, new java.awt.Color(102, 102, 102)));
        jPanel2.setPreferredSize(new java.awt.Dimension(480, 20));
        statusBarLabel.setFont(new java.awt.Font("Tahoma", 0, 11));
        statusBarLabel.setPreferredSize(new java.awt.Dimension(478, 16));
        statusBarLabel.setRequestFocusEnabled(false);
        jPanel2.add(statusBarLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jPanel2, gridBagConstraints);

        jFileMenu.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("file_menu"));
        newFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newFileMenuItem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("file_new_menu"));
        newFileMenuItem.setActionCommand("file_new");
        newFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jFileMenu.add(newFileMenuItem);
        newFileMenuItem.getAccessibleContext().setAccessibleName("file_new");

        fileOpenMenutem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        fileOpenMenutem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("file_open_menu"));
        fileOpenMenutem.setActionCommand("file_open");
        fileOpenMenutem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jFileMenu.add(fileOpenMenutem);
        fileOpenMenutem.getAccessibleContext().setAccessibleName("file_open");

        jFileMenu.add(jSeparator2);

        fileSaveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        fileSaveMenuItem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("file_save_menu"));
        fileSaveMenuItem.setActionCommand("file_save");
        fileSaveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jFileMenu.add(fileSaveMenuItem);
        fileSaveMenuItem.getAccessibleContext().setAccessibleName("save");

        saveAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        saveAsMenuItem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("file_save_as_menu"));
        saveAsMenuItem.setActionCommand("file_save_as");
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jFileMenu.add(saveAsMenuItem);
        saveAsMenuItem.getAccessibleContext().setAccessibleName("save_as");

        jFileMenu.add(jSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("file_exit_menu"));
        exitMenuItem.setActionCommand("exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        jFileMenu.add(exitMenuItem);

        jMenuBar1.add(jFileMenu);

        buildMenu.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("build_menu"));
        validateMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        validateMenuItem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("build_validate_menu"));
        validateMenuItem.setActionCommand("validate");
        validateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        buildMenu.add(validateMenuItem);

        buildPackageMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        buildPackageMenuItem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("build_build_menu"));
        buildPackageMenuItem.setActionCommand("pkg_build");
        buildPackageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        buildMenu.add(buildPackageMenuItem);

        jMenuBar1.add(buildMenu);

        helpMenu.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("help_menu"));
        helpMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        helpMenuItem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("help_help_menu"));
        helpMenuItem.setActionCommand("show_help");
        helpMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        helpMenu.add(helpMenuItem);

        licenseMenuItem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("help_license_menu"));
        licenseMenuItem.setActionCommand("show_license");
        licenseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        helpMenu.add(licenseMenuItem);

        faqMenuItem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("help_faq_menu"));
        faqMenuItem.setActionCommand("show_faq");
        faqMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        helpMenu.add(faqMenuItem);

        changesMenuItem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("help_changes_menu"));
        changesMenuItem.setActionCommand("show_changes");
        changesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        helpMenu.add(changesMenuItem);

        aboutMenuItem.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("help_about_menu"));
        aboutMenuItem.setActionCommand("show_about");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents
    
    private void mcChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcChooseButtonActionPerformed
        if ((baseDirTextField.getText() == null || baseDirTextField.getText().equals("")) ||
                (mainJarTextField.getText() == null || mainJarTextField.getText().equals(""))) {
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("bd_or_mj_isnt_set"), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("cant_select_mc"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        final String mainJarPath = baseDirTextField.getText() + '/' + mainJarTextField.getText();
        File file = new File(mainJarPath);
        
        if (!file.exists()) {
            JOptionPane.showMessageDialog(this, MessageFormat.format(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("mj_doesnt_exists"), new Object[]{mainJarPath }), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("cant_select_mc"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        final ArrayList mainClassesList = new ArrayList();
        
        try {
            final JarScanner scanner = new JarScanner(mainJarPath, mainClassesList);
            final JPackitProgressDialog progressDialog = new JPackitProgressDialog(this, MessageFormat.format(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("parsing_jar"), new Object[]{file.getAbsolutePath()}));
            Thread task = new Thread() {
                public void run() {
                    scanner.addNotificationListener(progressDialog);
                    progressDialog.setJPackitEventProducer(scanner);
                    try {
                        scanner.process();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            };
            progressDialog.setTask(task);
            progressDialog.doJob();
            
            if (scanner.isCancelled()) {
                return;
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, MessageFormat.format(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("cannot_parse_jar"), new Object[]{mainJarPath}), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("cant_select_mc"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (mainClassesList.isEmpty()) {
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("no_main_classes"), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("cant_select_mc"), JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        MainClassSelectorDialog dlg = new MainClassSelectorDialog(this, mainClassesList);
        int retCode = dlg.showDialog();
        if (retCode == MainClassSelectorDialog.OK) {
            mainClassTextField.setText(dlg.getMainClass());
            mainClassTextField.setToolTipText(dlg.getMainClass());
        }
    }//GEN-LAST:event_mcChooseButtonActionPerformed
    
    private void mjChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mjChooseButtonActionPerformed
        File baseDirFile = new File(baseDirTextField.getText());
        RelativeFileSystemView fsv = new RelativeFileSystemView(baseDirFile);
        JFileChooser fileChooser = new SafeFileChooser(baseDirFile, fsv);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setMultiSelectionEnabled(false);
        
        fileChooser.setFileFilter(new FileFilter() {
            public String getDescription() {
                return java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("jar_files");
            }
            
            public boolean accept(File file) {
                if (file.getName().endsWith(".jar") || file.isDirectory())
                    return true;
                else
                    return false;
            }
        });
        if (JFileChooser.APPROVE_OPTION == fileChooser.showDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("select_title"))) {
            File file = fileChooser.getSelectedFile();
            String relPath = Util.calculateRelativePath(baseDirTextField.getText(), file.getPath());
            mainJarTextField.setText(relPath);
            mainJarTextField.setToolTipText(relPath);
        }
    }//GEN-LAST:event_mjChooseButtonActionPerformed
    
    public void postInit() {
        baseDirTextField.getDocument().addDocumentListener(this);
        jarsLocationTextField.getDocument().addDocumentListener(this);
        pkgLocationTextField.getDocument().addDocumentListener(this);
        pkgNameTextField.getDocument().addDocumentListener(this);
        predefArgsTextField.getDocument().addDocumentListener(this);
        defaultArgsTextField.getDocument().addDocumentListener(this);
        mainClassTextField.getDocument().addDocumentListener(this);
        mainJarTextField.getDocument().addDocumentListener(this);
        pkgTypeComboBox.addItemListener(this);
        addWindowListener(this);
        statusBarLabel.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("status_bar_unsaved"));
        revalidateControls();
    }
    
    private void plChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plChooseButtonActionPerformed
        File baseDirFile = new File(baseDirTextField.getText());
        RelativeFileSystemView fsv = new RelativeFileSystemView(baseDirFile);
        JFileChooser fileChooser = new SafeFileChooser(baseDirFile, fsv);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        fileChooser.setFileFilter(new FileFilter() {
            public String getDescription() {
                return java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("dirs");
            }
            
            public boolean accept(File file) {
                if (file.isDirectory())
                    return true;
                else
                    return false;
            }
        });
        
        if (JFileChooser.APPROVE_OPTION == fileChooser.showDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("select_title"))) {
            File file = fileChooser.getSelectedFile();
            if (file.isDirectory() && Util.belongs(file.getAbsolutePath(), baseDirTextField.getText())) {
                pkgLocationTextField.setToolTipText(Util.calculateRelativePath(baseDirTextField.getText(), file.getAbsolutePath()));
                pkgLocationTextField.setText(Util.calculateRelativePath(baseDirTextField.getText(), file.getAbsolutePath()));
            }
        }
    }//GEN-LAST:event_plChooseButtonActionPerformed
    
    private void jlChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlChooseButtonActionPerformed
        // TODO add your handling code here:
        JarsChooserDialog jarsChooser = new JarsChooserDialog(this, true);
        jarsChooser.setBaseDir(baseDirTextField.getText());
        jarsChooser.setJarsList((ArrayList) jarsList.clone());
        if (JarsChooserDialog.OK == jarsChooser.showDialog()) {
            jarsList = (ArrayList) jarsChooser.getJarsList();
            if (jarsChooser.getJarsList().isEmpty()) {
                jarsLocationTextField.setToolTipText(null);
                jarsLocationTextField.setText(null);
            } else {
                jarsLocationTextField.setToolTipText(jarsChooser.getJarsList().toString());
                jarsLocationTextField.setText(jarsChooser.getJarsList().toString());
            }
        }
        
    }//GEN-LAST:event_jlChooseButtonActionPerformed
    
    private void bdChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdChooseButtonActionPerformed
        // TODO add your handling code here:
        if ((baseDirTextField.getText() != null && !baseDirTextField.getText().trim().equals("")) &&
                (jarsList.size() != 0 || 
                (pkgLocationTextField.getText() != null && !pkgLocationTextField.getText().trim().equals("")) || 
                (mainJarTextField.getText() != null && !mainJarTextField.getText().trim().equals("")) )) {
            int ret = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("bd_values_defined"), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("bd_change_warning"), JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            switch (ret) {
                case JOptionPane.NO_OPTION:
                    return;
                case JOptionPane.YES_OPTION:
                    break;
            }
        }
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileChooser.setFileFilter(new FileFilter() {
            public String getDescription() {
                return java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("dirs");
            }
            
            public boolean accept(File file) {
                if (file.isDirectory())
                    return true;
                else
                    return false;
            }
        });
        if (JFileChooser.APPROVE_OPTION == fileChooser.showDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("select_title"))) {
            baseDirTextField.setText(fileChooser.getSelectedFile().getAbsolutePath());
            baseDirTextField.setToolTipText(fileChooser.getSelectedFile().getAbsolutePath());
        }
        
    }//GEN-LAST:event_bdChooseButtonActionPerformed
    
    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        String actionCommand = evt.getActionCommand();
        if (actionCommand.equals("file_new")) {
            if (changed) {
                int ret = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("discard_changes_question"), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("new_bc"), JOptionPane.YES_NO_OPTION);
                switch (ret) {
                    case JOptionPane.NO_OPTION:
                        return;
                    case JOptionPane.YES_OPTION:
                        newBuildConfiguration();
                        break;
                }
            } else {
                newBuildConfiguration();
            }
        } else if (actionCommand.equals("file_open")) {
            if (changed) {
                int ret = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("discard_changes_question"), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("open_bc"), JOptionPane.YES_NO_OPTION);
                switch (ret) {
                    case JOptionPane.NO_OPTION:
                        return;
                    case JOptionPane.YES_OPTION:
                        break;
                }
            }
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setAcceptAllFileFilterUsed(false);
            fileChooser.setFileFilter(new FileFilter() {
                public String getDescription() {
                    return java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("jbc_title");
                }
                
                public boolean accept(File file) {
                    if (file.getName().endsWith(".pbc") || file.isDirectory())
                        return true;
                    else
                        return false;
                }
            });
            if (JFileChooser.APPROVE_OPTION == fileChooser.showDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("select_title"))) {
                //if file is manually misstyped in file open dialog and
                if (!fileChooser.getSelectedFile().canRead()) {
                    JOptionPane.showMessageDialog(this,MessageFormat.format(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("ñanno_read_file"), new Object[]{fileChooser.getSelectedFile().getAbsolutePath()}), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("file_open_error"), JOptionPane.WARNING_MESSAGE);
                } else {
                    bcFile = fileChooser.getSelectedFile();
                    openBuildConfiguration();
                    changed = false;
                    revalidateControls();
                }
            }
            
        } else if (actionCommand.equals("file_save")) {
            //validating build configuration
            BuildConfiguration b = getCurrentBuildConfiguration();
            BuildConfigurationError[] errors = BuildConfigurationValidator.validate(b);
            if (errors.length != 0) {
                ValidationErrorDialog dlg = new ValidationErrorDialog(this, errors);
                dlg.setLocationRelativeTo(this);
                dlg.setVisible(true);
                dlg.dispose();
                int ress = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("save_validation_error_question"), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("validation_error"), JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (ress == JOptionPane.NO_OPTION) {
                    return;
                }
            }
            
            if (bcFile == null) {
                chooseSaveLocation(null);
            }
            if (bcFile != null) {
                saveBuildConfiguration();
                revalidateControls();
            }
        } else if (actionCommand.equals("file_save_as")) {
            //validating build configuration
            BuildConfiguration b = getCurrentBuildConfiguration();
            BuildConfigurationError[] errors = BuildConfigurationValidator.validate(b);
            if (errors.length != 0) {
                ValidationErrorDialog dlg = new ValidationErrorDialog(this, errors);
                dlg.setLocationRelativeTo(this);
                dlg.setVisible(true);
                dlg.dispose();
                int ress = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("save_validation_error_question"), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("validation_error"), JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (ress == JOptionPane.NO_OPTION) {
                    return;
                }
            }
            
            if (chooseSaveLocation(null)) {
                saveBuildConfiguration();
                revalidateControls();
            }
        } else if (actionCommand.equals("pkg_build")) {
            BuildConfiguration b = getCurrentBuildConfiguration();
            BuildConfigurationError[] errors = BuildConfigurationValidator.validate(b);
            if (errors.length != 0) {
                ValidationErrorDialog dlg = new ValidationErrorDialog(this, errors);
                dlg.setLocationRelativeTo(this);
                dlg.setVisible(true);
                dlg.dispose();
                return;
            }
            final JPackitProgressDialog progressDialog = new JPackitProgressDialog(this, MessageFormat.format(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("building_package"), new Object[]{b.getPackageFileFullPath()}));
            Thread task = new Thread() {
                public void run() {
                    JarPackageBuilder jarPackageBuilder = new JarPackageBuilder();
                    jarPackageBuilder.addNotificationListener(progressDialog);
                    progressDialog.setJPackitEventProducer(jarPackageBuilder);
                    try {
                        jarPackageBuilder.buildPackage(getCurrentBuildConfiguration());
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            };
            progressDialog.setTask(task);
            progressDialog.doJob();
        } else if (actionCommand.equals("validate")) {
            BuildConfiguration b = getCurrentBuildConfiguration();
            BuildConfigurationError[] errors = BuildConfigurationValidator.validate(b);
            if (errors.length != 0) {
                ValidationErrorDialog dlg = new ValidationErrorDialog(this, errors);
                dlg.setLocationRelativeTo(this);
                dlg.setVisible(true);
                dlg.dispose();
            } else {
                JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("validation_succeeded"), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("validation_completed"), JOptionPane.INFORMATION_MESSAGE);
            }
        } else if (actionCommand.equals("show_help")) {
            if(helpDialog==null) {
                helpDialog = new HtmlShowDialog(this,false, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("help_help_menu"), MiscUtils.getResourceAsString("META-INF/desc.html"));
            }
            helpDialog.setVisible(true);
        } else if (actionCommand.equals("show_license")) {
            if(licenceDialog==null) {
                licenceDialog = new HtmlShowDialog(this,false, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("help_license_menu"), MiscUtils.getResourceAsString("META-INF/license.html"));
            }
            licenceDialog.setVisible(true);
        } else if (actionCommand.equals("show_faq")) {
            if(faqDialog==null) {
                faqDialog = new HtmlShowDialog(this,false, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("help_faq_menu"), MiscUtils.getResourceAsString("META-INF/faq.html"));
            }
            faqDialog.setVisible(true);
        } else if (actionCommand.equals("show_changes")) {
            if(changesDialog==null) {
                changesDialog = new HtmlShowDialog(this,false, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("help_changes_menu"), MiscUtils.getResourceAsString("META-INF/changes.html"));
            }
            changesDialog.setVisible(true);
        } 
        else if (actionCommand.equals("show_about")) {
            if(aboutDialog==null) {
                aboutDialog = new AboutJDialog(this);
            }
            aboutDialog.setLocationRelativeTo(this);
            aboutDialog.setVisible(true);
        } else if (actionCommand.equals("exit")) {
            quit();
        }
    }//GEN-LAST:event_menuActionPerformed
    
    private void newBuildConfiguration() {
        baseDirTextField.setText(null);
        jarsLocationTextField.setText(null);
        mainJarTextField.setText(null);
        pkgLocationTextField.setText(null);
        predefArgsTextField.setText(null);
        defaultArgsTextField.setText(null);
        mainClassTextField.setText(null);
        pkgNameTextField.setText(null);
        pkgTypeComboBox.setSelectedIndex(0);
        jarsList.clear();
        changed = false;
        bcFile = null;
        statusBarLabel.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("status_bar_unsaved"));
        revalidateControls();
    }
    
    private void openBuildConfiguration() {
        BuildConfiguration bc;
        try {
            FileInputStream fis = new FileInputStream(bcFile);
            PropertiesBuildConfigurationManager pbcm = new PropertiesBuildConfigurationManager();
            bc = pbcm.load(fis);
            fis.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, MessageFormat.format(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("status_bar_opened"), new Object[]{bcFile.getAbsolutePath()}), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("file_open_error"), JOptionPane.WARNING_MESSAGE);
            bcFile = null;
            return;
        }
        if (bc != null) {
            baseDirTextField.setText(bc.getBaseDir());
            baseDirTextField.setToolTipText(bc.getBaseDir());
            jarsList = (ArrayList) bc.getDependantJars();
            if (jarsList.isEmpty()) {
                jarsLocationTextField.setText(null);
                jarsLocationTextField.setToolTipText(null);
            } else {
                jarsLocationTextField.setText(jarsList.toString());
                jarsLocationTextField.setToolTipText(jarsList.toString());
            }
            pkgTypeComboBox.setSelectedItem(bc.getBuildType().getName());
            defaultArgsTextField.setText(bc.getDefaultArgs());
            predefArgsTextField.setText(bc.getPredefArgs());
            pkgLocationTextField.setText(bc.getPackageLocation());
            pkgLocationTextField.setToolTipText(bc.getPackageLocation());
            pkgNameTextField.setText(bc.getPackageName());
            mainClassTextField.setText(bc.getMainClass());
            mainClassTextField.setToolTipText(bc.getMainClass());
            mainJarTextField.setText(bc.getMainJar());
            mainJarTextField.setToolTipText(bc.getMainJar());
            changed = false;
            statusBarLabel.setText(MessageFormat.format(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("status_bar_opened"), new Object[]{bcFile.getAbsolutePath()}));
        }
    }
    
    private BuildConfiguration getCurrentBuildConfiguration() {
        BuildConfiguration bc = new BuildConfiguration();
        bc.setBaseDir(baseDirTextField.getText());
        bc.setDependantJars((List) jarsList.clone());
        bc.setBuildTypeByName((String) pkgTypeComboBox.getSelectedItem());
        bc.setDefaultArgs(defaultArgsTextField.getText());
        bc.setPredefArgs(predefArgsTextField.getText());
        bc.setPackageLocation(pkgLocationTextField.getText());
        bc.setPackageName(pkgNameTextField.getText());
        bc.setMainClass(mainClassTextField.getText());
        bc.setMainJar(mainJarTextField.getText());
        return bc;
    }
    
    private void saveBuildConfiguration() {
        BuildConfiguration bc = getCurrentBuildConfiguration();
        try {
            //adding file extention
            FileOutputStream fos = new FileOutputStream(bcFile);
            PropertiesBuildConfigurationManager pbcm = new PropertiesBuildConfigurationManager();
            pbcm.save(bc, fos);
            fos.flush();
            fos.close();
            changed = false;
            statusBarLabel.setText(MessageFormat.format(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("status_bar_saved"), new Object[]{bcFile.getAbsolutePath()}));
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,MessageFormat.format(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("couldnt_save_file_error"), new Object[]{bcFile.getAbsolutePath()}) , java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("file_save_error"), JOptionPane.WARNING_MESSAGE);
            bcFile = null;
            return;
        }
    }
    
    private boolean chooseSaveLocation(String startWith) {
        boolean retval = false;
        File oldBcFile = bcFile;
        JFileChooser fileChooser = new JFileChooser(startWith);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setDialogType(JFileChooser.SAVE_DIALOG);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setFileFilter(new FileFilter() {
            public String getDescription() {
                return java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("jbc_title");
            }
            
            public boolean accept(File file) {
                if (file.getName().endsWith(".pbc") || file.isDirectory())
                    return true;
                else
                    return false;
            }
        });
        if (JFileChooser.APPROVE_OPTION == fileChooser.showDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("save_title"))) {
            File file = fileChooser.getSelectedFile();
            
            //handling extension support
            if (!file.getAbsolutePath().endsWith(".pbc"))
                file = new File(file.getAbsolutePath() + ".pbc");
            
            if (file.exists()) {
                int ret = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("file_exists_question"), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("file_exists"), JOptionPane.YES_NO_OPTION);
                if (ret == JOptionPane.YES_OPTION) {
                    bcFile = file;
                    retval = true;
                }
            } else {
                bcFile = file;
                retval = true;
            }
        }
        
        if (retval) {
            boolean canWrite;
            try {
                new FileOutputStream(bcFile);
                canWrite = true;
            } catch (Exception e) {
                canWrite = false;
            }
            if (!canWrite) {
                int ret = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("unable_write_file_question"), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("error"), JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
                if (ret == JOptionPane.YES_OPTION) {
                    retval = chooseSaveLocation(bcFile.getAbsolutePath());
                } else {
                    retval = false;
                }
            }
        }
        if (!retval)
            bcFile = oldBcFile;
        return retval;
    }
    
    public void revalidateControls() {
        if (baseDirTextField.getText() == null || baseDirTextField.getText().trim().equals("")) {
            jlChooseButton.setEnabled(false);
            mcChooseButton.setEnabled(false);
            plChooseButton.setEnabled(false);
            mjChooseButton.setEnabled(false);
        }
        if (baseDirTextField.getText() != null && !baseDirTextField.getText().trim().equals("")) {
            jlChooseButton.setEnabled(true);
            mcChooseButton.setEnabled(true);
            plChooseButton.setEnabled(true);
            mjChooseButton.setEnabled(true);
        }
        if (changed) {
            ((TitledBorder) jPanel1.getBorder()).setTitle(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("bc_title") + " *");
            if (statusBarLabel.getText() != null && !statusBarLabel.getText().endsWith("*")) {
                statusBarLabel.setText(statusBarLabel.getText() + " *");
            }
        } else {
            ((TitledBorder) jPanel1.getBorder()).setTitle(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("bc_title"));
        }
        if (bcFile != null) {
            setTitle(bcFile.getAbsolutePath());
        }
        repaint();
    }
    
    private void quit() {
        if (changed) {
            while (true) {
                int res = JOptionPane.showConfirmDialog(this, java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("wanna_save_on_exit_question"), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("exit_application"), JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
                if (res == JOptionPane.YES_OPTION) {
                    if (bcFile == null) {
                        if (chooseSaveLocation(null)) {
                            saveBuildConfiguration();
                            
                            setVisible(false);
                            dispose();
                            Runtime.getRuntime().exit(0);
                            break;
                        } else {
                            continue;
                        }
                    } else {
                        saveBuildConfiguration();
                        setVisible(false);
                        dispose();
                        Runtime.getRuntime().exit(0);
                        break;
                    }
                } else if (res == JOptionPane.NO_OPTION) {
                    setVisible(false);
                    dispose();
                    Runtime.getRuntime().exit(0);
                    break;
                } else if (res == JOptionPane.CANCEL_OPTION) {
                    break;
                }
            }
        } else {
            setVisible(false);
            dispose();
            Runtime.getRuntime().exit(0);
        }
    }
    
    public boolean isChanged() {
        return changed;
    }
    
    public void setChanged(boolean changed) {
        this.changed = changed;
    }
    
    public void changedUpdate(javax.swing.event.DocumentEvent e) {
        changed = true;
        revalidateControls();
    }
    
    public void insertUpdate(javax.swing.event.DocumentEvent e) {
        changed = true;
        revalidateControls();
    }
    
    public void removeUpdate(javax.swing.event.DocumentEvent e) {
        changed = true;
        revalidateControls();
    }
    
    public void itemStateChanged(java.awt.event.ItemEvent e) {
        changed = true;
        revalidateControls();
    }
    
    public void windowActivated(java.awt.event.WindowEvent windowEvent) {
    }
    
    public void windowClosed(java.awt.event.WindowEvent windowEvent) {
    }
    
    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        quit();
    }
    
    public void windowDeactivated(java.awt.event.WindowEvent windowEvent) {
    }
    
    public void windowDeiconified(java.awt.event.WindowEvent windowEvent) {
    }
    
    public void windowIconified(java.awt.event.WindowEvent windowEvent) {
    }
    
    public void windowOpened(java.awt.event.WindowEvent windowEvent) {
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTextField baseDirTextField;
    private javax.swing.JButton bdChooseButton;
    private javax.swing.JMenu buildMenu;
    private javax.swing.JMenuItem buildPackageMenuItem;
    private javax.swing.JMenuItem changesMenuItem;
    private javax.swing.JTextField defaultArgsTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuItem faqMenuItem;
    private javax.swing.JMenuItem fileOpenMenutem;
    private javax.swing.JMenuItem fileSaveMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jarsLocationTextField;
    private javax.swing.JButton jlChooseButton;
    private javax.swing.JMenuItem licenseMenuItem;
    private javax.swing.JTextField mainClassTextField;
    private javax.swing.JTextField mainJarTextField;
    private javax.swing.JButton mcChooseButton;
    private javax.swing.JButton mjChooseButton;
    private javax.swing.JMenuItem newFileMenuItem;
    private javax.swing.JTextField pkgLocationTextField;
    private javax.swing.JTextField pkgNameTextField;
    private javax.swing.JComboBox pkgTypeComboBox;
    private javax.swing.JButton plChooseButton;
    private javax.swing.JTextField predefArgsTextField;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JLabel statusBarLabel;
    private javax.swing.JMenuItem validateMenuItem;
    // End of variables declaration//GEN-END:variables
    
}


/*
 * $Log: JFrameForm.java,v $
 * Revision 1.32  2005/02/11 09:33:56  kamil_sham
 * Added help and about dialogs. Fixed several bugs.
 *
 * Revision 1.31  2005/02/10 07:59:34  kamil_sham
 * *** empty log message ***
 *
 * Revision 1.30  2005/02/10 06:13:28  kamil_sham
 * Fixed i18n
 *
 * Revision 1.29  2005/02/09 08:15:19  kamil_sham
 * *** empty log message ***
 *
 * Revision 1.28  2005/02/07 13:11:05  kamil_sham
 * Moved all messages into resource bundle
 *
 * Revision 1.27  2005/02/07 12:47:41  kamil_sham
 * Moved all messages into i18n resources
 *
 * Revision 1.26  2005/02/01 07:26:36  kamil_sham
 * Fixed bug with abnormal program termination, centered JFrame window, and many other small bugs
 *
 * Revision 1.25  2005/02/01 05:39:58  kamil_sham
 * *** empty log message ***
 *
 * Revision 1.24  2005/01/28 12:01:33  kamil_sham
 * Added warning dialog when, trying to change baseDir with main jar already selected
 *
 * Revision 1.23  2005/01/28 11:25:27  kamil_sham
 * Changed font to Tahoma
 *
 * Revision 1.22  2005/01/26 08:24:37  kamil_sham
 * Fixed bug with changing base dir
 *
 * Revision 1.21  2005/01/24 19:03:28  kamil_sham
 * Added kunststoff look and feel, removed resizing from all windows.
 *
 * Revision 1.20  2005/01/24 18:37:39  kamil_sham
 * Added frame title
 *
 * Revision 1.19  2005/01/24 13:23:35  ignath
 * Refactored code
 *
 * Revision 1.18  2005/01/24 07:10:18  kamil_sham
 * Added support for default ars and predefined args, fixed NPE in Validator, changed build.xml to build jar_test package using commandline jar builder
 *
 * Revision 1.17  2005/01/20 21:27:25  kamil_sham
 * Fixed bug with jarsList reference sharing between JFrameForm and JarPackageBuilder
 *
 * Revision 1.16  2005/01/20 20:43:15  kamil_sham
 * Made massive refactoring to separate and unificate notification framework, added main class selector dialog, and progress bar
 *
 * Revision 1.15  2005/01/20 13:55:07  kamil_sham
 * Chenged label fron "jars location" to "dependant jars"
 *
 * Revision 1.14  2005/01/20 13:38:27  kamil_sham
 * Added mainJar field handling into gui,
 *
 * Revision 1.13  2005/01/20 13:00:33  kamil_sham
 * Added standard java properties based BuildConfiguration serialization
 *
 * Revision 1.12  2005/01/20 12:39:26  ignath
 * Added "main jar" field to build configuration
 *
 * Revision 1.11  2005/01/14 13:54:17  kamil_sham
 * Disabled predef and default args
 *
 * Revision 1.10  2005/01/14 12:15:30  kamil_sham
 * *** empty log message ***
 *
 * Revision 1.9  2005/01/14 06:36:25  kamil_sham
 * Fixed bug 1101720	Cancel button has strange behavior in jar chooser dialog
 *
 * Revision 1.8  2005/01/14 06:15:07  kamil_sham
 * Fixed some bugs
 *
 * Revision 1.7  2005/01/13 08:15:40  kamil_sham
 * Fixed bugs 1101464-Save file problem and 1101461 - Add validation to ui
 *
 * Revision 1.6  2005/01/13 07:35:16  kamil_sham
 * Fixed several bugs and added validation support in ui
 *
 * Revision 1.5  2005/01/13 06:06:35  kamil_sham
 * Fixed compilation bug concerned ArrayList substitution
 *
 * Revision 1.4  2005/01/13 06:04:00  kamil_sham
 * Change jarsList from List to ArrayList, it prevented project compilation
 *
 * Revision 1.3  2005/01/12 15:04:25  ignath
 * Added jars validation and main class validation to BuildConfigurationValidator.
 
 * Replaced ArrayList to interface List where it was appropriate.
 *
 * Revision 1.2  2005/01/12 11:12:33  ignath
 * Fixed bug with selection of build type when opening build configuration file
 *
 * Revision 1.1  2005/01/12 09:25:47  kamil_sham
 * *** empty log message ***
 *
 * Revision 1.14  2005/01/11 12:12:04  ignath
 * Added good file header and footer
 *
 */