/*
 * Copyright 2004-2005 Ignat Aleksandrov, Kamil Shamgunov
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package net.sf.jpackit.ui.swing;

import net.sf.jpackit.notification.JPackitEventProducer;
import net.sf.jpackit.notification.JPackitNotificationListener;

import javax.swing.*;

/**
 * Progress dialog for package building process
 *
 * @author Kamil K. Shamgunov
 */

public class JPackitProgressDialog extends java.awt.Dialog implements JPackitNotificationListener {
    private Thread task;
    private JPackitEventProducer eventProducer;

    /**
     * Creates new form BuildPackageProgressDialog
     */
    public JPackitProgressDialog(java.awt.Frame parent, String title) {
        super(parent, true);
        setTitle(title);
        this.setTask(task);
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        stateString = new javax.swing.JLabel();
        buildingProgressBar = new javax.swing.JProgressBar();
        cancelButton = new javax.swing.JButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(340, 80));
        stateString.setPreferredSize(new java.awt.Dimension(300, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(stateString, gridBagConstraints);

        buildingProgressBar.setPreferredSize(new java.awt.Dimension(300, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(buildingProgressBar, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel1.add(cancelButton, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        stateString.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("cancelling_in_progress"));
        eventProducer.cancelAction();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    public void errorMessageChanged(net.sf.jpackit.notification.JPackitNotificationEvent event) {
        JOptionPane.showMessageDialog(this, event.getMessage(), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("pkg_building_error"), JOptionPane.ERROR_MESSAGE);
        setVisible(false);
        dispose();
    }

    public void actionInterrupted() {
        stateString.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("canceled"));
        setVisible(false);
        dispose();
    }

    public void progressInfoChanged(net.sf.jpackit.notification.JPackitNotificationEvent event) {
        int pbValue = Integer.parseInt(event.getMessage());
        buildingProgressBar.setValue(pbValue);
        if (pbValue == 100) {
            setVisible(false);
            dispose();
        }
    }

    public void stateChanged(net.sf.jpackit.notification.JPackitNotificationEvent event) {
        stateString.setText(event.getMessage());
    }

    public void doJob() {
        pack();
        setLocationRelativeTo(getParent());
        getTask().start();
        setVisible(true);
    }

    public Thread getTask() {
        return task;
    }

    public void setTask(Thread task) {
        this.task = task;
    }

    public JPackitEventProducer getJPackitEventProducer() {
        return eventProducer;
    }

    public void setJPackitEventProducer(JPackitEventProducer eventProducer) {
        this.eventProducer = eventProducer;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar buildingProgressBar;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel stateString;
    // End of variables declaration//GEN-END:variables

}


/*
 * $Log: JPackitProgressDialog.java,v $
 * Revision 1.4  2005/02/11 09:33:57  kamil_sham
 * Added help and about dialogs. Fixed several bugs.
 *
 * Revision 1.3  2005/02/07 13:11:05  kamil_sham
 * Moved all messages into resource bundle
 *
 * Revision 1.2  2005/01/24 13:23:35  ignath
 * Refactored code
 *
 * Revision 1.1  2005/01/20 20:43:15  kamil_sham
 * Made massive refactoring to separate and unificate notification framework, added main class selector dialog, and progress bar
 *
 * Revision 1.4  2005/01/14 12:15:30  kamil_sham
 * *** empty log message ***
 *
 * Revision 1.3  2005/01/14 11:19:10  ignath
 * Added possibility to cancel building process
 *
 * Revision 1.2  2005/01/14 06:15:07  kamil_sham
 * Fixed some bugs
 *
 * Revision 1.1  2005/01/12 09:25:47  kamil_sham
 * *** empty log message ***
 *
 * Revision 1.3  2005/01/11 12:12:04  ignath
 * Added good file header and footer
 *
 */