/*
 * Copyright 2004-2005 Ignat Aleksandrov, Kamil Shamgunov
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package net.sf.jpackit.ui.swing;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

/**
 * Main class chooser dialog
 *
 * @author Kamil K. Shamgunov
 */

public class MainClassSelectorDialog extends javax.swing.JDialog {
    public static final int OK = 0;
    public static final int CANCEL = 1;
    public int retCode;
    private ArrayListListModel listModel;
    private String mainClass;

    /**
     * Creates new form MainClassSelectorDialog
     */
    public MainClassSelectorDialog(java.awt.Frame parent, ArrayList mainClasses) {
        super(parent, true);
        listModel = new ArrayListListModel(mainClasses);
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainClassesList = new javax.swing.JList();
        selectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102)), java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("class_chooser_panel_title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 250));
        mainClassesList.setModel(listModel);
        mainClassesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainClassesListMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(mainClassesList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        selectButton.setText(java.util.ResourceBundle.getBundle("net/sf/jpackit/ui/swing/messages").getString("select_button"));
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(selectButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(cancelButton, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void mainClassesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainClassesListMouseClicked
        int count = evt.getClickCount();
        if (count == 2) {
            int index = mainClassesList.locationToIndex(evt.getPoint());
            if (index != -1) {
                mainClass = (String) listModel.getElementAt(index);
                retCode = OK;
                setVisible(false);
            }
        }
    }//GEN-LAST:event_mainClassesListMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        retCode = CANCEL;
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        if (mainClassesList.getSelectedValue() == null) return;
        mainClass = (String) mainClassesList.getSelectedValue();
        retCode = OK;
        setVisible(false);
    }//GEN-LAST:event_selectButtonActionPerformed

    public int showDialog() {
        setLocationRelativeTo(getParent());
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                retCode = CANCEL;
            }
        });
        this.setVisible(true);
        return retCode;
    }

    public String getMainClass() {
        return mainClass;
    }

    public void setMainClass(String mainClass) {
        this.mainClass = mainClass;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList mainClassesList;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables

}
/*
 * $Log: MainClassSelectorDialog.java,v $
 * Revision 1.5  2005/02/07 13:11:05  kamil_sham
 * Moved all messages into resource bundle
 *
 * Revision 1.4  2005/01/24 19:03:30  kamil_sham
 * Added kunststoff look and feel, removed resizing from all windows.
 *
 * Revision 1.3  2005/01/24 18:32:49  kamil_sham
 * fixed build.xml to leave command line client in build directory. Fixed class file comments, added javadocs
 *
 */